### ISSUE TITLE
sentenceRE ‘s finetune codes can't reproduce successfully

### ISSUE THREAD

**Issue by zweny** [thunlp/ERICA#7]
Hi! here is a problem and need your help
After run 'bash run.sh' ，the code suspended in main.py [line 125] 

> loss, output = model(**inputs) 

for a long time
```
Namespace(adam_epsilon=1e-08, batch_size_per_gpu=32, ckpt_to_load='../pretrain/ckpt/ERICA_bert_uncased_RP', cuda='0', dataset='tacred', encoder='bert', entity_marker=True, gpu=device(type='cuda'), hidden_size=768, lr=3e-05, max_epoch=8, max_grad_norm=1, max_length=100, mode='CM', optim='adamw', seed=42, train_prop=1.0, warmup_steps=500, weight_decay=1e-05)
Use all train data!
pre process train.txt
The number of sentence in which tokenizer can't find head/tail entity is 0
pre process dev.txt
The number of sentence in which tokenizer can't find head/tail entity is 0
pre process test.txt
The number of sentence in which tokenizer can't find head/tail entity is 0
********* load from ckpt/../pretrain/ckpt/ERICA_bert_uncased_RP ***********
successful load ckpt
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
Begin train...
We will train model in 17032 steps
```
i tried to delete the specific [main.py/line 103]  **'model = nn.DataParallel(model)'** and add '**model.cuda()**' .but get error: 
```
Traceback (most recent call last):
  File "main.py", line 311, in <module>
    train(args, model, train_dataloader, dev_dataloader, test_dataloader)
  File "main.py", line 131, in train
    loss, output = model(**inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ERICA/finetune/Sent_level_RE/code/re/model.py", line 36, in forward
    outputs = self.bert(input_ids, mask)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_bert.py", line 753, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_bert.py", line 178, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select
```
Is it possible that the batch data[main.py/line:114] is stored in the CPU while the model is stored in the GPU?

**Comment by zweny** [comment]
This problem may be caused by a mismatch between the CUDA version(11.0) and the required PyTorch version(1.5.0).I will try again after changing the image.

**Comment by zweny** [comment]
Yep, this issue caused by the mismatch between cuda and pytorch version .
Btw, if someone wanna reproduce this code with multiple cuda，you might notice that **the LOSS's value[line:125] is a tensor which size is 1*the number of cuda**, you may need to add a line 'loss = loss.sum()'.
